### ISSUE TITLE
Click 'Group Existing Tabs' yields no response; 

### ISSUE THREAD

**Issue by hfguo02** [MichaelYuhe/ai-group-tabs#41]
## Description
checking the Chrome extensions reveals an error prompt.

## Error log
```
Error in event handler: TypeError: Cannot read properties of undefined (reading '0') at chrome-extension://gnclkpnopkmphjkajnolljlogjmoglec/service_worker.js:1:313 at Array.forEach (<anonymous>) at chrome-extension://gnclkpnopkmphjkajnolljlogjmoglec/service_worker.js:1:295
```
```
TypeError: Cannot read properties of undefined (reading '0')
```
```
import{g as s}from"./utils.fb-KO4Ve.js";async function f(n,e,r){const o=n.map(t=>({id:t.id,title:t.title,url:t.url})),a=e.map(t=>({type:t,tabIds:[]})),i=await s("model")||"gpt-4",c=await s("apiURL")||"https://api.openai.com";try{return await Promise.all(o.map(async t=>{if(!t.url)return;const p=(await(await fetch(`${c}/v1/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${r}`},body:JSON.stringify({messages:[{role:"system",content:"You are a classificator"},{role:"user",content:`Based on the URL ${t.url}, classify the browser tab type as one of the following: ${e.join(", ")}. Respond with only the classification keyword from the list.`}],model:i})})).json()).choices[0].message.content,l=e.indexOf(p);l!==-1&&a[l].tabIds.push(t.id)})),a}catch(t){return console.error(t),a}}async function u(n,e,r){try{const o=await s("model")||"gpt-4",a=await s("apiURL")||"https://api.openai.com";return(await(await fetch(`${a}/v1/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${r}`},body:JSON.stringify({messages:[{role:"system",content:"You are a classificator"},{role:"user",content:`Based on the URL ${n.url}, classify the browser tab type as one of the following: ${e.join(", ")}. Respond with only the classification keyword from the list.`}],model:o})})).json()).choices[0].message.content}catch(o){console.error(o)}}export{f as b,u as h};
```

**Comment by hfguo02** [comment]
![image](https://github.com/MichaelYuhe/ai-group-tabs/assets/81001788/b94dde31-1435-4136-bf97-d6d3674e2630)

**Comment by hfguo02** [comment]
The selected model, GPT-3.5, cannot be used properly.

**Comment by MichaelYuhe** [comment]
Did u try other models? can they work normally?

**Comment by GentlemanHu** [comment]
Same here, all models not working

<img width="672" alt="image" src="https://github.com/MichaelYuhe/ai-group-tabs/assets/34559079/7abce40f-ead6-4f8a-8489-b08678c761e9">

---
---


> Stack Trace

```javascript
import{g as r}from"./utils.Xiu07ssm.js";async function m(n,e,o){const a=n.map(t=>({id:t.id,title:t.title,url:t.url})),s=e.map(t=>({type:t,tabIds:[]})),i=await r("model")||"gpt-3.5-turbo",c=await r("apiURL")||"https://api.openai.com/v1/chat/completions";try{return await Promise.all(a.map(async t=>{if(!t.url)return;const p=(await(await fetch(c,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${o}`,"Api-Key":o},body:JSON.stringify({messages:[{role:"system",content:"You are a classificator"},{role:"user",content:`Based on the URL: "${t.url}" and title: "${t.title}", classify the browser tab type as one of the following: ${e.join(", ")}. Respond with only the classification keyword from the list.`}],model:i})})).json()).choices[0].message.content,l=e.indexOf(p);l!==-1&&s[l].tabIds.push(t.id)})),s}catch(t){return console.error(t),s}}async function f(n,e,o){try{const a=await r("model")||"gpt-3.5-turbo",s=await r("apiURL")||"https://api.openai.com/v1/chat/completions";return(await(await fetch(s,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${o}`,"Api-Key":o},body:JSON.stringify({messages:[{role:"system",content:"You are a classificator"},{role:"user",content:`Based on the URL: "${n.url}" and title: "${n.title}", classify the browser tab type as one of the following: ${e.join(", ")}. Respond with only the classification keyword from the list.`}],model:a})})).json()).choices[0].message.content}catch(a){console.error(a)}}export{m as b,f as h};
```

**Comment by GentlemanHu** [comment]
Using openai alternative api, seems apiURL not read from options config.

<img width="753" alt="image" src="https://github.com/MichaelYuhe/ai-group-tabs/assets/34559079/bbd68796-27b0-40de-8467-8aaf60580fcf">


<img width="527" alt="image" src="https://github.com/MichaelYuhe/ai-group-tabs/assets/34559079/909f0800-3949-451a-aacd-0fbcc8f79a7e">

**Comment by MichaelYuhe** [comment]
<img width="423" alt="image" src="https://github.com/MichaelYuhe/ai-group-tabs/assets/63531512/3ddc5dc7-41a5-49e6-8226-42d460e2b992">
It should be working, can u check the network in the Network panel?

**Comment by GentlemanHu** [comment]
no log in Network panel
<img width="1372" alt="image" src="https://github.com/MichaelYuhe/ai-group-tabs/assets/34559079/cae877d2-05fb-4c0c-85f8-3779f0c86e69">

**Comment by MichaelYuhe** [comment]
You need to check in service_worker console

**Comment by hfguo02** [comment]
I think found the reason,I created my own Assistants ChatGPT 3.5-turbo model on OpenAI and am verifying if my key works.

I'm not sure if there is a necessary connection, but it is currently working fine.

**Comment by GentlemanHu** [comment]
Yes, maybe the config not saved if not close Options tab; after closing Options tab, my config works.
